name: phonio
author: Kim Rostgaard Christensen (BitStack)
version: 0.0.4+experimental
description: A basic framework for interfacing with SIP phones.
dependencies:
  logging: any
  shelf: any
  shelf_exception_response: any
  shelf_route: any
  shelf_web_socket: any
