name: phonio
version: 0.0.15+experimental
author: Kim Rostgaard Christensen (BitStackers)
description: A basic framework for interfacing with SIP phones.
dependencies:
  logging: any
  shelf: any
  shelf_exception_response: any
  shelf_route: any
  shelf_web_socket: any
