name: phonio
version: 0.0.90
author: Kim Rostgaard Christensen (BitStackers)
description: A basic framework for interfacing with SIP phones.
dependencies:
  logging: any
  shelf: any
  shelf_route: any
  shelf_web_socket: any
